// places.dart — the Mercator map's place-name layer.
//
// assets/geo/places.json is generated by tool/make_places.py from Natural
// Earth 10m populated places (public domain), Europe only: rows of
// [name, lat, lng, scalerank], most important first. Cities only — Natural
// Earth has no small towns. The layer exists so the VHF map has something to
// aim at when zoomed in close (e.g. Münster from Lengerich), where the
// country outlines alone show blank land.
//
// Same loading contract as WorldGeometry: lazy one-shot singleton, and a
// malformed asset yields an empty list — never a crash.

import 'dart:convert';

import 'package:flutter/services.dart' show rootBundle;

import 'projection.dart';

/// One named place. [rank] is Natural Earth's scalerank (0 = most important).
typedef Place = ({String name, LatLng pos, int rank});

class Places {
  Places._();
  static final Places instance = Places._();

  static const String _assetPath = 'assets/geo/places.json';

  List<Place>? _places;
  Future<List<Place>>? _pending;

  /// Places already loaded, or empty while the load is pending.
  List<Place> get loaded => _places ?? const [];

  Future<List<Place>> load() {
    if (_places != null) return Future.value(_places);
    return _pending ??= () async {
      final list = parse(await rootBundle.loadString(_assetPath));
      _places = list;
      _pending = null;
      return list;
    }();
  }

  /// Pure parser (unit-tested). Rows that do not have the expected shape are
  /// skipped; unparsable input yields an empty list.
  static List<Place> parse(String json) {
    dynamic j;
    try {
      j = jsonDecode(json);
    } catch (_) {
      return const [];
    }
    if (j is! List) return const [];
    final out = <Place>[];
    for (final row in j) {
      if (row is! List || row.length < 4) continue;
      final (name, lat, lng, rank) = (row[0], row[1], row[2], row[3]);
      if (name is! String || lat is! num || lng is! num || rank is! num) continue;
      out.add((name: name, pos: (lat: lat.toDouble(), lng: lng.toDouble()), rank: rank.toInt()));
    }
    return out;
  }

  /// Highest scalerank shown at a Mercator zoom level: capitals only when
  /// zoomed out, cities down to rank 10 from zoom 7 up.
  static int maxRankForZoom(double zoom) {
    if (zoom < 3) return 1;
    if (zoom < 4) return 3;
    if (zoom < 5) return 5;
    if (zoom < 6) return 7;
    if (zoom < 7) return 8;
    return 10;
  }
}
